lab13/modelforms/modelforms/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

lab13/modelforms/employee/models.py
from django.db import models

class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

lab13/modelforms/employee/forms.py
from django import forms
from employee.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

lab13/modelforms/employee/views.py
from django.shortcuts import render, redirect
from employee.forms import EmployeeForm
from employee.models import Employee

def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            
            except:
                pass
    
    else:
        form = EmployeeForm()
        
    return render(request, 'index.html', {'form': form})

def show(request):
    employees = Employee.objects.all()
    
    return render(request, "show.html", {'employees': employees})

def edit(request, id):
    employee = Employee.objects.get(id=id)
    
    return render(request, 'edit.html', {'employee': employee})

def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    
    if form.is_valid():
        form.save()
        return redirect("/show")
    
    return render(request, 'edit.html', {'employee': employee})

def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    
    return redirect("/show")

lab13/modelforms/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Изменение сотрудника</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <form method="POST" class="post-form" action="/update/{{ employee.id }}">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Изменить детали</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Id сотрудника:</label>
          <div class="col-sm-4">
            <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}" />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Имя сотрудника:</label>
          <div class="col-sm-4">
            <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Email сотрудника:</label>
          <div class="col-sm-4">
            <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Контакт сотрудника:</label>
          <div class="col-sm-4">
            <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-primary">Изменить</button>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>

lab13/modelforms/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Добавление сотрудника</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <form method="POST" class="post-form" action="/emp">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Ввести детали</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Id сотрудника:</label>
          <div class="col-sm-4">{{ form.eid }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Имя сотрудника:</label>
          <div class="col-sm-4">{{ form.ename }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Email сотрудника:</label>
          <div class="col-sm-4">{{ form.eemail }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Контакт сотрудника:</label>
          <div class="col-sm-4">{{ form.econtact }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-primary">Подтвердить</button>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>

lab13/modelforms/templates/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Отображение списка сотрудников</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <div class="container">
      <br />
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Сотрудники</h3>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <a class="btn btn-primary" href="/emp">Добавить нового сотрудника</a>
        </div>
      </div>
      <br />
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id сотрудника</th>
            <th>Имя сотрудника</th>
            <th>Email сотрудника</th>
            <th>Контакт сотрудника</th>
            <th>Действия</th>
          </tr>
        </thead>
        <tbody>
          {% for employee in employees %}
            <tr>
              <td>{{ employee.eid }}</td>
              <td>{{ employee.ename }}</td>
              <td>{{ employee.eemail }}</td>
              <td>{{ employee.econtact }}</td>
              <td>
                <a class="btn btn-info" href="/edit/{{ employee.id }}">Изменить</a>
                <a class="btn btn-danger" href="/delete/{{ employee.id }}">Удалить</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
</html>